name: PatsWeb

on:
  push:
  # pull_request:
  #   branches:
  #     - main  # Set a branch to deploy
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout Web Repo
        uses: actions/checkout@v2
        with:
          repository: davidgs/PatsWeb
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
          path: ./PatsWeb
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.81.0'
      - name: Build
        run: cd PatsWeb; hugo --minify
      # - name: rsync deployments
      #   uses: burnett01/rsync-deployments@4.1
      #   with:
      #     switches: -avzr
      #     path: ./PatsWeb/public/
      #     remote_path: /home/${{ secrets.SSH_USER }}/www/patrick
      #     remote_host: ${{ secrets.SSH_HOST }}
      #     remote_port: ${{ secrets.SSH_PORT }}
      #     remote_user: ${{ secrets.SSH_USER }}
      #     remote_key: ${{ secrets.WEBSITE_DEPLOY_KEY }}
